site:
  production_url: "http://js.gelistiriciyiz.biz"
  title: "JavaScript Püf Noktaları"
  subtitle: "JavaScript ile ilgili Türkçe püf noktaları"
  tag_line: "Gündelik Hayatta JavaScript"
  description: "JavaScript ile ilgili Türkçe püf noktaları"
  logo: "logo.png"
  cover_image: "cover.png"
  social:
    twitter: "js_tips_tr"
    # facebook: ""
  company:
    name: "Geliştiriciyiz.biz"
    url: "http://gelistiriciyiz.biz/"
  product:
    name: "GELİŞTİRİCİYİZ.BİZ"
    url: "http://gelistiriciyiz.biz/"
  main_author:
    name: "Full Name"
    email: "email@example.com"
    link: "http://example.com"
    bio: "Title"